name: Publish to NPM

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run npm publish with --dry-run'
        required: false
        default: false
        type: boolean
      tag:
        description: 'Tag for pre-release'
        required: false
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: drgrove/gimlijs-tools@sha256:44c8dabd2a14f259f935113ab84a0bf86c02a986092e3120fcf16d14f97dda15

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      run: |
        git config --global --add safe.directory $PWD
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git fetch --depth=1 origin ${{ github.sha }}
        git checkout FETCH_HEAD
        test "$(git rev-parse HEAD)" = "${{ github.sha }}"

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Publish to NPM
      run: |
        npm publish \
          --provenance \
          ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }} \
          ${{ github.event.inputs.tag != '' && format('--tag {0}', github.event.inputs.tag) || '' }} \
          --access public

