name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: drgrove/gimlijs-tools@sha256:2008d786b0ce031301d1b2ded77d71649a5b488492e789485a6fd467ba4a37df

    steps:
    - name: Checkout code
      run: |
        git config --global --add safe.directory /__w/gimli.js/gimli.js
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git fetch --depth=1 origin ${{ github.event.after }}
        git checkout FETCH_HEAD

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Run tests
      run: npm test
